# Generated by Django 4.1.3 on 2022-12-24 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kişi', 'verbose_name_plural': 'Kişiler'},
        ),
        migrations.AlterModelOptions(
            name='restoran',
            options={'verbose_name': 'Restoran', 'verbose_name_plural': 'Restoranlar'},
        ),
        migrations.AlterField(
            model_name='person',
            name='duty_type',
            field=models.CharField(choices=[('1', 'Görevli'), ('2', 'Kurucu'), ('3', 'Müdür'), ('4', 'Aşçı')], max_length=1, verbose_name='görev'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, verbose_name='cinsiyet'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='image_name',
            field=models.CharField(max_length=50, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
