# Generated by Django 4.1.3 on 2022-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0002_alter_person_options_alter_restoran_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoran',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restoran',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
