# Generated by Django 4.1.3 on 2022-12-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0003_restoran_is_active_restoran_is_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='acıktın.restoran')),
            ],
        ),
    ]
