# Generated by Django 4.1.3 on 2022-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
