# Generated by Django 4.1.3 on 2022-12-27 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='description',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='image_cover',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='image_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='language',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Başlık'),
        ),
        migrations.CreateModel(
            name='Menuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Özet')),
                ('image_name', models.CharField(default=None, max_length=50, verbose_name='Resim')),
                ('image_cover', models.CharField(default=None, max_length=50)),
                ('date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=19)),
                ('language', models.CharField(default=None, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('restoranConnect', models.ManyToManyField(to='acıktın.restoran')),
            ],
        ),
    ]
