# Generated by Django 4.1.3 on 2022-12-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0005_comment_email_comment_full_name_comment_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuler',
            old_name='slug',
            new_name='slug2',
        ),
    ]
