# Generated by Django 4.1.3 on 2022-12-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acıktın', '0006_rename_slug_menuler_slug2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuler',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menuler'},
        ),
    ]
